spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
